const { createConcert, deleteConcert, getConcert } = require('../controllers/concertController')
const upload = require('../middleware/upload')
const express = require('express')
const requireAuth = require('../middleware/requireAuth')
const router = express.Router()
router.use(requireAuth)
router.post('/', upload.single('poster'), createConcert)
router.delete('/:id', deleteConcert)
router.get('/:id', getConcert)
module.exports = router