const { createMovie, deleteMovie, getMovie } = require('../controllers/movieController')
const upload = require('../middleware/upload')
const express = require('express')
const requireAuth = require('../middleware/requireAuth')
const router = express.Router()
router.use(requireAuth)
router.post('/', upload.single('poster'), createMovie)
router.delete('/:id', deleteMovie)
router.get('/:id', getMovie)
module.exports = router