const { getShows, createShow, deleteShow, getTheatreByMovie, getMovieByTheatre } = require('../controllers/showsController')
const express = require('express')
const requireAuth = require('../middleware/requireAuth')
const router = express.Router()
router.use(requireAuth)
router.get('/', getShows)
router.post('/', createShow)
router.delete('/:id', deleteShow)
router.get('/bymovie', getTheatreByMovie)
router.get('/bytheatre', getMovieByTheatre)
module.exports = router