const { getTheatres, createTheatre, deleteTheatre, getTheatre } = require('../controllers/theatreController')
const express = require('express')
const requireAuth = require('../middleware/requireAuth')
const router = express.Router()
router.use(requireAuth)
router.get('/', getTheatres)
router.post('/', createTheatre)
router.delete('/:id', deleteTheatre)
router.get('/:id', getTheatre)
module.exports = router